/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,njk,js}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#003941",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "secondary": "#00677d",
        "on-secondary-container": "#005c70",
        "secondary-container": "#50d9fe",
        "inverse-on-surface": "#eff1f3",
        "on-primary-container": "#799dd6",
        "on-tertiary-fixed": "#001f24",
        "primary-fixed": "#d5e3ff",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "secondary-fixed": "#b3ebff",
        "on-tertiary-fixed-variant": "#004f59",
        "on-secondary-fixed": "#001f27",
        "on-primary-fixed-variant": "#1f477b",
        "primary-container": "#003366",
        "surface-container-high": "#e6e8ea",
        "background": "#f7f9fb",
        "tertiary-fixed": "#9feffe",
        "on-secondary": "#ffffff",
        "surface-tint": "#3a5f94",
        "tertiary": "#002227",
        "on-secondary-fixed-variant": "#004e5f",
        "inverse-primary": "#a7c8ff",
        "outline": "#737780",
        "on-primary-fixed": "#001b3c",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a7c8ff",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d1",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#43474f",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4cd6fb",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        "primary": "#001e40",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
